name: MineguildAdmin
main: com.github.mineguild.MineguildAdmin.Main
version: 0.3.5
website: http://www.mineguild.de
author: Mineguild-TechAdmins
description: >
             A Plugin made by the Mineguild Admins
commands: