name: MineguildAdmin
main: com.github.mineguild.MineguildAdmin.Main
version: 0.1
commands:
    test:
        description: Test command
        usage: /test [player]
        permission: mga.test
        permission-message: You don´t have permissions to do this.