name: MineguildAdmin
main: com.github.mineguild.MineguildAdmin.Main
version: 0.2
commands:
    vers:
        description: Display version
        usage: /mga vers
        permission: mga.vers
        permission-message: You dont have permissions to do this.
    test:
        description: Test command
        usage: /test
        permission: mga.test
        permission-message: You dont have permissions to do this.
