name: MineguildAdmin
main: com.github.mineguild.MineguildAdmin.Main
version: 0.1
commands:
    test:
        description: Test command
        usage: /version [player]
        permission: mga.test
        permission-message: You dont have permissions to do this.