name: MineguildAdmin
main: com.github.mineguild.MineguildAdmin.Main
version: 0.3
commands:
    mga:
        description: Basic MGA command
        usage: Unknown Command. Usage: /mga help
        permission: mga.mga
        permission-message: You dont have permissions to do this.