name: MineguildAdmin
main: com.github.mineguild.MineguildAdmin.Main
version: 0.3.5
website: http://www.mineguild.de
author: Mineguild-TechAdmins
description: >
             A Plugin made by the Mineguild Admins
commands:
    mga:
        description: Basic MGA command
        usage: Unknown Command. Usage /mga help
        permission: mga.mga
        permission-message: You dont have permissions to do this.
    gm:
        description: Change gamemode
        usage: /gm [player]
        permission: mga.gm
        permission-message: You dont have permissions to do this.
    heal:
        description: Heals you or the targeted player.
        usage: /heal [player]
        permission: mga.heal
        permission-message: You dont have permissions to do this.
    check:
        description: Checks player stats.
        usage: /check [player]
        permission: mga.check
        permission-message: You dont have permissions to do this.
    feed:
        description: feeds
        usage: /feed [player]
        permission: mga.feed
        permission-message: You dont have permissions to do this.
    spawn:
        description: Teleport to spawn
        usage: /spawn
        permission: mga.spawn
        permission-message: You dont have permissions to do this.
    setspawn:
        description: Sets the spawn-location
        usage: /setspawn
        permission: mga.setspawn
        permission-message: You dont have permissions to do this.
    i:
        description: Gives items. WARNING!!! Only type correct item names.
        usage: /i [item] [amount]
        permission: mga.i
        permission-message: You dont have permissions to do this.